---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - legator.io
  resources:
  - agentenvironments
  - agentruns
  - legators
  - modeltierconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - legator.io
  resources:
  - agentenvironments/finalizers
  - agentruns/finalizers
  - legators/finalizers
  - modeltierconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - legator.io
  resources:
  - agentenvironments/status
  - agentruns/status
  - legators/status
  - modeltierconfigs/status
  verbs:
  - get
  - patch
  - update
