apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  labels:
    app.kubernetes.io/name: legator
    app.kubernetes.io/managed-by: kustomize
  name: legator-sample
spec:
  # TODO(user): Add fields here
